jobs:
  # Build job
  build:
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: "18"
        cache: pnpm

    - name: Install dependencies
      run: pnpm install

    - name: Static HTML export from nuxt
      run: pnpm nuxt generate

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./output/public

  # Deploy job
  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
